weights: /home/wqg/pyproject/git/yolo/yolov7-pose_Npoint_Ncla/runs/train/exp8/weights/best.pt
cfg: cfg/yolov7-tiny-pose.yaml
data: data/plate.yaml
hyp: data/hyp.pose.yaml
epochs: 100
batch_size: 4
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: true
local_rank: -1
workers: 4
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze: 0
kpt_label: true
world_size: 1
global_rank: -1
save_dir: runs/train/exp12
total_batch_size: 4
